"""add_file_path_to_claim_documents

Revision ID: 5bc394fafc73
Revises: e829db4f40cf
Create Date: 2026-06-16 15:19:26.819838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc394fafc73'
down_revision: Union[str, Sequence[str], None] = 'e829db4f40cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_documents', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_documents', 'file_path')
    # ### end Alembic commands ###
