"""initial_claims_tables

Revision ID: e829db4f40cf
Revises: 
Create Date: 2026-06-16 13:45:21.593538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e829db4f40cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('claim_category', sa.String(), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failed_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_member_id'), 'claims', ['member_id'], unique=False)
    op.create_table('claim_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_documents_claim_id'), 'claim_documents', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_documents_claim_id'), table_name='claim_documents')
    op.drop_table('claim_documents')
    op.drop_index(op.f('ix_claims_member_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
