LOG_FILE_PATH = f"/logs/claimpilot"
INQ_REQ_RESP_INITIAL_FILE_NAME = "_CLAIMPILOT_REQ_RESP"
ERROR_INITIAL_FILE_NAME = "_CLAIMPILOT_ERROR"
ACCESS_FILE_NAME = "_access"
APPLICATION_FILE_NAME = "_CLAIMPILOT_APPLOGS"

X_Trace_ID = "X_Trace_ID"